### ISSUE TITLE
Foundry 11: websocket.js:52 Uncaught (in promise) ReferenceError: releaseURLs is not defined

### ISSUE THREAD

**Issue by coffiarts** [ParticulaCode/FoundryVTT-GoDice#24]
In my Foundry 11 session, trying to connect to GoDice on my Android device, I am consistently getting the below error in my Chrome console (in addition, the menu item "Open Dice Configuration" has never once shown up in my Foundry session):
```
GoDice websocket connection opened

3dice-connection.mjs:54 GoDice websocket message received

websocket.js:52 Uncaught (in promise) ReferenceError: releaseURLs is not defined
    at analyzeWSmessage (websocket.js:52:47)
    at ws.onmessage (websocket.js:187:9)
analyzeWSmessage @ websocket.js:52
ws.onmessage @ websocket.js:187
```
As you can see, there is at least SOME successful connection between GoDice and my Foundry instance, but then it fails repeatedly.
**Any idea?**

**My setup:**
- Foundry 11 (latest stable version)
- Chrome (latest version)
- GoDice Chrome extension installed
- GoDice app running fine in WS (non secure) mode on my Android device (connected through local WiFi)
- Foundry game instance is running in local LAN on a local PC, over https with a self-signed vcertificate (everything running fine apart from the GoDice connection). BUT IT MAKES NOT DIFFERENCE if I switch my Foundry server to plain http and GoDice to ws, and then connect to my Foundry game through http => error persists!
- Configured my Chrome browser to accept "mixed connections" (https to ws) from my url GoDice ws url (ws://192.168.1.104:8596), according to the instructions at https://stackoverflow.com/questions/67765238/mixed-content-the-page-at-was-loaded-over-https-but-requested-an-insecure-resour
- Module "Go Dice Bluetooth Dice" and "Unfulfilled Rolls" installed properly and running without  any console erros (apart from tha one shown above)
- running "wscat -c ws://192.168.1.104:8596" from command line on my PC (where the Foundry server is running) returns: "error: Unexpected server response: 501"

**Comment by coffiarts** [comment]
UPDATE: Did some more research. It actually seems that my GoDice IS connected to my game, because whenever doing a manual GoDice roll, the result seems to be logged in the console:
![image](https://github.com/ParticulaCode/FoundryVTT-GoDice/assets/39616483/e240bb53-2b89-47cf-998a-b94484ed8de8)
But I do NOT see the "Open Dice Configuration" option, thus I am unable to set a BT provider, and so none of my rolls gets registered in game.
So I guess that my core issue boils down to the question: Why can't I see the "Open Dice Configuration" option?

**Comment by coffiarts** [comment]
Seems I was mislead by another module (Material Deck). Though I still can't get GoDice to work, the specific error above turns out to derive from MD instead. Closing this issue myself. Sorry for the confusion.
