### ISSUE TITLE
Results of roll not shown with d100% and Dice So Nice enabled

### ISSUE THREAD

**Issue by achetzel** [ParticulaCode/FoundryVTT-GoDice#6]
Foundry 11.302 
WFRP 6.5.9
Dice-So-Nice 4.6.8

When Dice So Nice is enabled the d100% roll is not applied to the card (and the card is not shown either). The following error is in the console:

```
DiceBox.js:567 Uncaught TypeError: Cannot read properties of null (reading 'shape')
    at DiceBox.getVectors (DiceBox.js:567:16)
    at DiceBox.js:1079:20
    at Array.forEach (<anonymous>)
    at DiceBox.start_throw (DiceBox.js:1065:10)
    at Dice3D.js:759:34
    at Dice3D.js:473:17```

When the module is disabled or disabled only for the user, the roll goes through fine.

**Comment by achetzel** [comment]
Corrected along with https://github.com/ParticulaCode/FoundryVTT-GoDice/issues/5
